openapi: 3.0.3
info:
  title: Endoz API
  description: API for endoz openbanking platform.
  version: 1.0.0
servers:
  - url: https://endozapi.celergate.net
    description: Sandbox Environment
paths:
  /login/:
    post:
      tags:
        - Authentication
      parameters:
        - name: X-CLIENTID
          in: header
          required: true
          description: Client identifier for the API.
          schema:
            type: string
          example: sdfgfd-sdfgf4d-sdfgfdsd-sdfgfds
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  description: The email address of the user.
                  example: test@example.com
                public_key:
                  type: string
                  description: The client public key.
                  example: 1e89ffb6-5a40-4df1-b1b9-ff1c832214f0
                secret_key:
                  type: string
                  description: The client secret key.
                  example: sdfgfd-sdfgf4d-sdfgfdsd-sdfgfds
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  access:
                    type: string
                    description: The access token for the session.
                  refresh:
                    type: string
                    description: The refresh token for the session.
                example:
                  access: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ...
                  refresh: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ...
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    description: Error message describing why the request failed.
                example:
                  detail: Invalid email or public key.
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    description: Error message for unauthorized access.
                example:
                  detail: Missing or invalid X-CLIENTID header.
  /initiate-payment/:
    post:
      summary: Initiate a payment
      tags:
        - Payments
      parameters:
        - name: X-CLIENTID
          in: header
          required: true
          description: Client identifier for the API.
          schema:
            type: string
          example: sdfgfd-sdfgf4d-sdfgfdsd-sdfgfds
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
                  description: The amount to be paid.
                  example: 5
                currency:
                  type: string
                  description: The currency of the payment.
                  example: "GBP"
                settlement_account:
                  type: string
                  description: The account to settle the payment.
                  example: "987d28af0d"
                transaction_ref:
                  type: string
                  description: Reference for the transaction.
                  example: "34534redf3d00"
                narration:
                  type: string
                  description: A description or reason for the payment.
                  example: "Gift"
                webhook_url:
                  type: string
                  description: URL for webhook notifications related to this payment.
                  example: "https://webhook.site/481927c8-36d7-4cc0-a9de-49562206d9b1"
                redirect_url:
                  type: string
                  description: URL to redirect after payment.
                  example: "https://wikipedia.com"
                payer:
                  type: object
                  description: Information about the payer.
                  properties:
                    first_name:
                      type: string
                      description: First name of the payer.
                      example: "Ahmad"
                    last_name:
                      type: string
                      description: Last name of the payer.
                      example: "Sharafudeen"
                    email_address:
                      type: string
                      description: Email address of the payer.
                      example: "ahmadsharafudeen@gmail.com"
                    address:
                      type: string
                      description: Address of the payer.
                      example: "Lugbe, Abuja"
      responses:
        '200':
          description: Payment initiated successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  reference:
                    type: string
                    description: Reference for the payment.
                  hosted_url:
                    type: string
                    description: URL to redirect to for payment.
                example:
                  reference: "202503131111096386ed356c98f9a4"
                  hosted_url: "https://endozpay.celergate.net?payload=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXltZW50X2lkIjo1MywicmVmZXJlbmNlIjoiMzQ1MzRyZWRmM2QwMCIsImFtb3VudCI6NS4wLCJjdXJyZW5jeSI6Ilx1MDBhMyIsImNsaWVudCI6IkVuZG96IERldiJ9.qC5iILRh0zmSD0jMpY4Csv9UZHBZ3sGmcCFipGzz6qs"
        '400':
          description: Bad Request - Invalid data or missing required fields.
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    description: Error message for the bad request.
                example:
                  detail: "Invalid payment details."
        '401':
          description: Unauthorized - Missing or invalid `X-CLIENTID` header.
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    description: Error message for unauthorized access.
                example:
                  detail: Missing or invalid X-CLIENTID header.
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    description: Error message describing the server error.
                example:
                  detail: An internal server error occurred.
  '/payments/{transaction_ref}/':
    get:
      summary: Retrieve payment details
      tags:
        - Payments
      parameters:
        - name: transaction_ref
          in: path
          required: true
          description: Reference for the transaction.
          schema:
            type: string
          example: 34534redf3d00
      responses:
        '200':
          description: Payment details retrieved successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: Unique identifier for the payment.
                    example: 53
                  our_reference:
                    type: string
                    description: Internal reference for the payment.
                    example: "202503131111096386ed356c98f9a4"
                  amount:
                    type: string
                    description: Amount of the payment.
                    example: "5.00"
                  transaction_ref:
                    type: string
                    description: Reference for the transaction.
                    example: "34534redf3d00"
                  currency_code:
                    type: string
                    description: Currency code of the payment.
                    example: "GBP"
                  currency_symbol:
                    type: string
                    description: Currency symbol of the payment.
                    example: "£"
                  narration:
                    type: string
                    description: Description or reason for the payment.
                    example: "Gift"
                  status:
                    type: string
                    description: Status of the payment.
                    example: "PENDING"
                  payer_name:
                    type: string
                    description: Name of the payer.
                    example: ""
                  metadata:
                    type: object
                    description: Additional metadata for the payment.
                    nullable: true
                  webhook_url:
                    type: string
                    description: URL for webhook notifications related to this payment.
                    example: "https://webhook.site/481927c8-36d7-4cc0-a9de-49562206d9b1"
                  redirect_url:
                    type: string
                    description: URL to redirect after payment.
                    example: "https://wikipedia.com"
                  created_on:
                    type: string
                    format: date-time
                    description: Timestamp when the payment was created.
                    example: "2025-03-13T11:11:09.638493Z"
                  institution_code:
                    type: string
                    description: Institution code related to the payment.
                    example: ""
        '404':
          description: Payment not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    description: Error message for missing payment.
                example:
                  detail: "Payment not found."
  '/payments/':
    get:
      summary: Payment history
      tags:
        - Payments
      parameters:
        - name: settlement_account_identifier
          in: query
          required: false
          description: settlement_account_identifier.
          schema:
            type: string
          example: 34534redf3d00
        - name: transaction_ref
          in: query
          required: false
          description: Reference for the transaction.
          schema:
            type: string
          example: 34534redf3d00
      responses:
        '200':
          description: Payment history retrieved successfully.
          content:
            application/json:
              type: object
              properties:
                count:
                  type: integer
                  example: 120
                next:
                  type: string
                  nullable: true
                  example: null
                previous:
                  type: string
                  nullable: true
                  example: null
                results:
                  type: array
                  items:
                    $ref: '#/components/schemas/Payment'
                  
        '404':
          description: Payment not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    description: Error message for missing payment.
                example:
                  detail: "Payment not found."

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Payment:
      type: object
        properties:
          id:
            type: integer
            description: Unique identifier for the payment.
            example: 53
          our_reference:
            type: string
            description: Internal reference for the payment.
            example: "202503131111096386ed356c98f9a4"
          amount:
            type: string
            description: Amount of the payment.
            example: "5.00"
          transaction_ref:
            type: string
            description: Reference for the transaction.
            example: "34534redf3d00"
          currency_code:
            type: string
            description: Currency code of the payment.
            example: "GBP"
          currency_symbol:
            type: string
            description: Currency symbol of the payment.
            example: "£"
          narration:
            type: string
            description: Description or reason for the payment.
            example: "Gift"
          status:
            type: string
            description: Status of the payment.
            example: "PENDING"
          payer_name:
            type: string
            description: Name of the payer.
            example: ""
          metadata:
            type: object
            description: Additional metadata for the payment.
            nullable: true
          webhook_url:
            type: string
            description: URL for webhook notifications related to this payment.
            example: "https://webhook.site/481927c8-36d7-4cc0-a9de-49562206d9b1"
          redirect_url:
            type: string
            description: URL to redirect after payment.
            example: "https://wikipedia.com"
          created_on:
            type: string
            format: date-time
            description: Timestamp when the payment was created.
            example: "2025-03-13T11:11:09.638493Z"
          institution_code:
            type: string
            description: Institution code related to the payment.
            example: ""